// Loaded Class
const $LayerBlock = Java.loadClass('com.ordana.immersive_weathering.blocks.LayerBlock')
const $BarrelBlock = Java.loadClass('net.minecraft.world.level.block.BarrelBlock')
const $ChairBlock = Java.loadClass('com.mrcrayfish.furniture.refurbished.block.ChairBlock')
const $Properties = Java.loadClass('net.minecraft.world.level.block.state.BlockBehaviour$Properties')
const $BlockItem = Java.loadClass('net.minecraft.world.item.BlockItem')
const $IProperties = Java.loadClass('net.minecraft.world.item.Item$Properties')
const $SoundType = Java.loadClass('net.minecraft.world.level.block.SoundType')
const $WoodType = Java.loadClass('net.minecraft.world.level.block.state.properties.WoodType')
const $DyeColor = Java.loadClass('net.minecraft.world.item.DyeColor')
const $SofaBlock = Java.loadClass('com.mrcrayfish.furniture.refurbished.block.SofaBlock')