StartupEvents.registry("block", (event) => {

  // Tinker Blocks
  event.create("crumbling_seared_bricks")
    .soundType("stone")
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll('kubejs:block/crumbling_seared_bricks')

  event.create("crumbling_scorched_bricks")
    .soundType("tuff")
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll('kubejs:block/crumbling_scorched_bricks')

  // Applied Blocks
  event.create('crashed_applied_controller') // Create a new block with ID "kubejs:example_block"
    .mapColor('heavy_metal') // Set a material (affects the sounds and some properties)
    .soundType('metal')
    .hardness(4.0) // Set hardness (affects mining time)
    .resistance(6.0) // Set resistance (to explosions, etc)
    .requiresTool(true) // Requires a tool or it won't drop (see tags below)
    .tagBlock('mineable/pickaxe') // or a pickaxe
    .tagBlock('minecraft:needs_iron_tool') // the tool tier must be at least iron
    .textureAll('kubejs:block/ae2_controller_crash')

  event.create('crashed_me_drive')
    .mapColor('heavy_metal')
    .soundType('metal')
    .hardness(4.0)
    .resistance(6.0)
    .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection.opposite))
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

  event.create('crashed_crafting_unit')
    .mapColor('heavy_metal')
    .soundType('metal')
    .hardness(4.0)
    .resistance(6.0)
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

  event.create('crashed_me_interface')
    .mapColor('heavy_metal')
    .soundType('metal')
    .hardness(4.0)
    .resistance(6.0)
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

  event.create('controller_frame')
    .mapColor('heavy_metal')
    .soundType('metal')
    .hardness(4.0)
    .resistance(6.0)
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .textureAll('kubejs:block/controller_frame')
	.defaultCutout()

  // Bigger Reactor Blocks
  event.create("crashed_reactor_controller")
    .mapColor("heavy_metal")
    .soundType("copper")
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll('kubejs:block/reactor_controller_crash')

  event.create("crashed_reactor_frame")
    .mapColor("heavy_metal")
    .soundType("copper")
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll('kubejs:block/reactor_frame_crash')

  event.create("crashed_turbine_controller")
    .mapColor("heavy_metal")
    .soundType("copper")
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll('kubejs:block/turbine_controller_crash')

  event.create("crashed_turbine_wall")
    .mapColor("heavy_metal")
    .soundType("copper")
    .hardness(1.0)
    .resistance(1.0)
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .textureAll('kubejs:block/turbine_wall_crash')

  // Pneumatic Blocks
  event.create('crashed_refinery')
    .mapColor('heavy_metal')
    .soundType('metal')
    .hardness(4.0)
    .resistance(6.0)
    .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection))
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

  event.create('crashed_refinery_output')
    .mapColor('heavy_metal')
    .soundType('metal')
    .hardness(4.0)
    .resistance(6.0)
    .property(BlockProperties.FACING)
    .defaultState(state => state.setValue(BlockProperties.FACING, Direction.NORTH))
    .placementState(state => state.setValue(BlockProperties.FACING, state.horizontalDirection))
    .requiresTool(true)
    .tagBlock('mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

  event.create("crashed_pressure_chamber_wall")
    .mapColor("heavy_metal")
    .soundType("metal")
    .hardness(4.0)
    .resistance(6.0)
    .requiresTool(true)
    .tagBlock("mineable/pickaxe")
    .tagBlock('minecraft:needs_iron_tool')
})