name = "Desolate Planet"
author = "Pawjwp"
version = "1.8.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daf53ce31f85cbd08899bf9609cef46fb5720c713d3bdcd739a7856802c279d8"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
