name = "Desolate Planet"
author = "Pawjwp"
version = "1.7.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72b21d5517f1197bf83351d9541f347d0e632b5f639c67c59cb2b536ee156907"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
