name = "Desolate Planet"
author = "Pawjwp"
version = "1.8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "751f5c2837217f3a61e2777cf76604e299f1740740df56a644ac5fbaa4b5cf48"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
