name = "Desolate Planet"
author = "Pawjwp"
version = "1.7.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60c2d94fffe01543306646646f7aec48479375cfa020812de090218ebf3ca57d"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
