name = "Desolate Planet"
author = "Pawjwp"
version = "1.8.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2b38d2d67cdd54ae0a7a21f6221e22b70f640619f242ffac4ca5b76efbfecd4"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
